### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by darrickyong** [darrickyong/earmark#2]
# User Auth
​
## Functionality
​
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
​
### Before Login
​
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
​
### After Login
​
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
​
​
## Style
​
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production
​
## Seeds
- [x] Adequate and appropriate seeds

### Comments
- [x] reduce width of text on splash page
- [x] add border radius to input boxes on session form
- [x] remove grey border on Login and Sign Up bottons _in the session form_
- [x] increase the size of your pig icon a bit on session form
- [x] update icon in navbar show on session form (pig blends in) flip the colors of the pig for the navbar version?
- [x] Add footer for session form / rest of your site 
- [x] Increase the height of the navbar a little (too squished)
- [x] Increase height of input box for name in sign up & email &password fields a little too
- [x] add "focus" glow to input box for name on signup
- [x] Add a fun little greyed out sentence below your session forms to make it look complete (like where splitwise has "forgot your password? and "By signing up, you accept the Splitwise Terms of Service. Don't use USD for currency? Click here."
- [x] everything moves on the login form if I don't enter anything and then click "login"

**Comment by jenvomo** [comment]
It's looking awesome @darrickyong !! Left some items to update some styling stuff.  Let me know when you're done and I'll review again.

**Comment by jenvomo** [comment]
Well done @darrickyong !
